apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsite
  namespace: personal-site-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsite
  template:
    metadata:
      labels:
        app: devsite
    spec:
      securityContext:
        fsGroup: 10001

      containers:
        - name: devsite
          image: ghcr.io/blakeridgway/personal-devsite
          ports:
            - containerPort: 5002
          env:
            - name: DATA_DIR
              value: /personalsite/data
          readinessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /personalsite/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: devsite-data