apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsite
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsite
  template:
    metadata:
      labels:
        app: devsite
    spec:
      containers:
        - name: devsite
          image: ghcr.io/blakeridgway/personal-devsite
          ports:
            - containerPort: 5002
          readinessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 15