apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsite
  namespace: dev
spec:
  ingressClassName: public
  rules:
    - host: dev.blakeridgway.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsite
                port:
                  number: 80