apiVersion: v1
kind: Secret
metadata:
  name: cycling-secrets
  namespace: personal-site-dev
type: Opaque
stringData:
  INTERVALS_API_KEY: "46yfxg5rajxscqfcnqjr4dpuv"
  INTERVALS_ATHLETE_ID: "i161950"